package org.fengxiaodong.db.bean;

import java.time.LocalDateTime;

public class GroupBuy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.good_id
     *
     * @mbg.generated
     */
    private Integer goodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.sum
     *
     * @mbg.generated
     */
    private Integer sum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.current_number
     *
     * @mbg.generated
     */
    private Integer currentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.origin_price
     *
     * @mbg.generated
     */
    private Double originPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.sponsor_price
     *
     * @mbg.generated
     */
    private Double sponsorPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.group_price
     *
     * @mbg.generated
     */
    private Double groupPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group_buy.deadline_time
     *
     * @mbg.generated
     */
    private LocalDateTime deadlineTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.id
     *
     * @return the value of group_buy.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.id
     *
     * @param id the value for group_buy.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.good_id
     *
     * @return the value of group_buy.good_id
     *
     * @mbg.generated
     */
    public Integer getGoodId() {
        return goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.good_id
     *
     * @param goodId the value for group_buy.good_id
     *
     * @mbg.generated
     */
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.user_id
     *
     * @return the value of group_buy.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.user_id
     *
     * @param userId the value for group_buy.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.sum
     *
     * @return the value of group_buy.sum
     *
     * @mbg.generated
     */
    public Integer getSum() {
        return sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.sum
     *
     * @param sum the value for group_buy.sum
     *
     * @mbg.generated
     */
    public void setSum(Integer sum) {
        this.sum = sum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.current_number
     *
     * @return the value of group_buy.current_number
     *
     * @mbg.generated
     */
    public Integer getCurrentNumber() {
        return currentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.current_number
     *
     * @param currentNumber the value for group_buy.current_number
     *
     * @mbg.generated
     */
    public void setCurrentNumber(Integer currentNumber) {
        this.currentNumber = currentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.origin_price
     *
     * @return the value of group_buy.origin_price
     *
     * @mbg.generated
     */
    public Double getOriginPrice() {
        return originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.origin_price
     *
     * @param originPrice the value for group_buy.origin_price
     *
     * @mbg.generated
     */
    public void setOriginPrice(Double originPrice) {
        this.originPrice = originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.sponsor_price
     *
     * @return the value of group_buy.sponsor_price
     *
     * @mbg.generated
     */
    public Double getSponsorPrice() {
        return sponsorPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.sponsor_price
     *
     * @param sponsorPrice the value for group_buy.sponsor_price
     *
     * @mbg.generated
     */
    public void setSponsorPrice(Double sponsorPrice) {
        this.sponsorPrice = sponsorPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.group_price
     *
     * @return the value of group_buy.group_price
     *
     * @mbg.generated
     */
    public Double getGroupPrice() {
        return groupPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.group_price
     *
     * @param groupPrice the value for group_buy.group_price
     *
     * @mbg.generated
     */
    public void setGroupPrice(Double groupPrice) {
        this.groupPrice = groupPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.status
     *
     * @return the value of group_buy.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.status
     *
     * @param status the value for group_buy.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.update_time
     *
     * @return the value of group_buy.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.update_time
     *
     * @param updateTime the value for group_buy.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.create_time
     *
     * @return the value of group_buy.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.create_time
     *
     * @param createTime the value for group_buy.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group_buy.deadline_time
     *
     * @return the value of group_buy.deadline_time
     *
     * @mbg.generated
     */
    public LocalDateTime getDeadlineTime() {
        return deadlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group_buy.deadline_time
     *
     * @param deadlineTime the value for group_buy.deadline_time
     *
     * @mbg.generated
     */
    public void setDeadlineTime(LocalDateTime deadlineTime) {
        this.deadlineTime = deadlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodId=").append(goodId);
        sb.append(", userId=").append(userId);
        sb.append(", sum=").append(sum);
        sb.append(", currentNumber=").append(currentNumber);
        sb.append(", originPrice=").append(originPrice);
        sb.append(", sponsorPrice=").append(sponsorPrice);
        sb.append(", groupPrice=").append(groupPrice);
        sb.append(", status=").append(status);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", deadlineTime=").append(deadlineTime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        GroupBuy other = (GroupBuy) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getGoodId() == null ? other.getGoodId() == null : this.getGoodId().equals(other.getGoodId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSum() == null ? other.getSum() == null : this.getSum().equals(other.getSum()))
            && (this.getCurrentNumber() == null ? other.getCurrentNumber() == null : this.getCurrentNumber().equals(other.getCurrentNumber()))
            && (this.getOriginPrice() == null ? other.getOriginPrice() == null : this.getOriginPrice().equals(other.getOriginPrice()))
            && (this.getSponsorPrice() == null ? other.getSponsorPrice() == null : this.getSponsorPrice().equals(other.getSponsorPrice()))
            && (this.getGroupPrice() == null ? other.getGroupPrice() == null : this.getGroupPrice().equals(other.getGroupPrice()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getDeadlineTime() == null ? other.getDeadlineTime() == null : this.getDeadlineTime().equals(other.getDeadlineTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getGoodId() == null) ? 0 : getGoodId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSum() == null) ? 0 : getSum().hashCode());
        result = prime * result + ((getCurrentNumber() == null) ? 0 : getCurrentNumber().hashCode());
        result = prime * result + ((getOriginPrice() == null) ? 0 : getOriginPrice().hashCode());
        result = prime * result + ((getSponsorPrice() == null) ? 0 : getSponsorPrice().hashCode());
        result = prime * result + ((getGroupPrice() == null) ? 0 : getGroupPrice().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getDeadlineTime() == null) ? 0 : getDeadlineTime().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER"),
        goodId("good_id", "goodId", "INTEGER"),
        userId("user_id", "userId", "INTEGER"),
        sum("sum", "sum", "INTEGER"),
        currentNumber("current_number", "currentNumber", "INTEGER"),
        originPrice("origin_price", "originPrice", "DOUBLE"),
        sponsorPrice("sponsor_price", "sponsorPrice", "DOUBLE"),
        groupPrice("group_price", "groupPrice", "DOUBLE"),
        status("status", "status", "TINYINT"),
        updateTime("update_time", "updateTime", "TIMESTAMP"),
        createTime("create_time", "createTime", "TIMESTAMP"),
        deadlineTime("deadline_time", "deadlineTime", "TIMESTAMP");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table group_buy
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}