package org.fengxiaodong.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fengxiaodong.db.bean.Bargain;
import org.fengxiaodong.db.bean.BargainExample;

public interface BargainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    long countByExample(BargainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    int deleteByExample(BargainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    int insert(Bargain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    int insertSelective(Bargain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Bargain selectOneByExample(BargainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Bargain selectOneByExampleSelective(@Param("example") BargainExample example, @Param("selective") Bargain.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Bargain> selectByExampleSelective(@Param("example") BargainExample example, @Param("selective") Bargain.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    List<Bargain> selectByExample(BargainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Bargain selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Bargain.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    Bargain selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Bargain record, @Param("example") BargainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Bargain record, @Param("example") BargainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Bargain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bargain
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Bargain record);
}