package org.fengxiaodong.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fengxiaodong.db.bean.Good;
import org.fengxiaodong.db.bean.GoodExample;

public interface GoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    long countByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int deleteByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int insert(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int insertSelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Good selectOneByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Good selectOneByExampleSelective(@Param("example") GoodExample example, @Param("selective") Good.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Good> selectByExampleSelective(@Param("example") GoodExample example, @Param("selective") Good.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    List<Good> selectByExample(GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Good selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Good.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    Good selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Good record, @Param("example") GoodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Good record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table good
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Good record);
}