package org.fengxiaodong.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fengxiaodong.db.bean.GroupBuy;
import org.fengxiaodong.db.bean.GroupBuyExample;

public interface GroupBuyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    long countByExample(GroupBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    int deleteByExample(GroupBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    int insert(GroupBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") GroupBuy record, @Param("selective") GroupBuy.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupBuy selectOneByExample(GroupBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupBuy selectOneByExampleSelective(@Param("example") GroupBuyExample example, @Param("selective") GroupBuy.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<GroupBuy> selectByExampleSelective(@Param("example") GroupBuyExample example, @Param("selective") GroupBuy.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    List<GroupBuy> selectByExample(GroupBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    GroupBuy selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") GroupBuy.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    GroupBuy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") GroupBuy record, @Param("example") GroupBuyExample example, @Param("selective") GroupBuy.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GroupBuy record, @Param("example") GroupBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") GroupBuy record, @Param("selective") GroupBuy.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<GroupBuy> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table group_buy
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<GroupBuy> list, @Param("selective") GroupBuy.Column ... selective);
}